import { createContext, useContext, useState } from 'react';

const GalleryContext = createContext();

const initialWorks = [
  { id: 1, title: 'Cosmic Dreams', artist: 'StellarArt', category: 'nft', image: `${import.meta.env.BASE_URL}images/cosmic-dreams.jpg`, price: '0.5 ETH', description: 'A journey through the cosmos.' },
  { id: 2, title: 'Neon City', artist: 'CyberPunk', category: 'photo', image: `${import.meta.env.BASE_URL}images/neon-city.jpg`, price: '0.8 ETH', description: 'Cyberpunk city vibes.' },
  { id: 3, title: 'Abstract Mind', artist: 'CreativeSoul', category: 'painting', image: `${import.meta.env.BASE_URL}images/abstract-mind.jpg`, price: '0.3 ETH', description: 'Abstract expressionism.' },
  { id: 4, title: 'AI Genesis', artist: 'BotMaster', category: 'ai', image: `${import.meta.env.BASE_URL}images/ai-genesis.jpg`, price: '0.1 ETH', description: 'Generated by AI.' },
  { id: 5, title: '3D Cube', artist: 'RenderGod', category: '3d', image: `${import.meta.env.BASE_URL}images/3d-cube.jpg`, price: '1.2 ETH', description: 'High fidelity 3D render.' },
  { id: 6, title: 'Nature Whisper', artist: 'EcoArt', category: 'photo', image: `${import.meta.env.BASE_URL}images/nature-whisper.jpg`, price: '0.4 ETH', description: 'Nature photography.' },
];

export function GalleryProvider({ children }) {
  const [works, setWorks] = useState(initialWorks);

  const addWork = (work) => {
    setWorks((prev) => [
      {
        id: Date.now(),
        ...work,
      },
      ...prev,
    ]);
  };

  return (
    <GalleryContext.Provider value={{ works, addWork }}>
      {children}
    </GalleryContext.Provider>
  );
}

export const useGallery = () => useContext(GalleryContext);
